import type { RecordType } from "@/lib/domain/record-types"

export const COMBINATION_CODES = [
  "THEORY",
  "MOOC",
  "PRACTICE",
  "WORKSHOP",
  "PROJECT",
  "THESIS",
  "INTERNSHIP",
  "THEORY_PRACTICE",
  "THEORY_PROJECT",
  "THEORY_PRACTICE_PROJECT",
  "PRACTICE_PROJECT",
  "THEORY_WORKSHOP",
] as const

export type CombinationCode = (typeof COMBINATION_CODES)[number]

export const SUBJECT_RECORD_MAP: Record<CombinationCode, readonly RecordType[]> = {
  THEORY: ["CLASSROOM_LEARNING"],
  MOOC: ["CLASSROOM_LEARNING"],
  PRACTICE: ["APPLIED_ACTION_LEARNING"],
  WORKSHOP: ["ACTION_LEARNING"],
  PROJECT: ["PROJECT_REPORT"],
  THESIS: ["THESIS_REPORT"],
  INTERNSHIP: ["INTERNSHIP_REPORT"],
  THEORY_PRACTICE: ["CLASSROOM_LEARNING", "APPLIED_ACTION_LEARNING"],
  THEORY_PROJECT: ["CLASSROOM_LEARNING", "PROJECT_REPORT"],
  THEORY_PRACTICE_PROJECT: [
    "CLASSROOM_LEARNING",
    "APPLIED_ACTION_LEARNING",
    "PROJECT_REPORT",
  ],
  PRACTICE_PROJECT: ["APPLIED_ACTION_LEARNING", "PROJECT_REPORT"],
  THEORY_WORKSHOP: ["CLASSROOM_LEARNING", "ACTION_LEARNING"],
}

export function requiredRecordTypes(code: CombinationCode): readonly RecordType[] {
  return SUBJECT_RECORD_MAP[code]
}
